## Setup

In [4]:
import numpy as np

In [5]:
import pandas as pd

In [8]:
import matplotlib

In [7]:
import seaborn

## Basic Data Structure

In [9]:
sr=pd.Series([1,3,5,7])
sr

0    1
1    3
2    5
3    7
dtype: int64

In [12]:
sr2=pd.Series([1,3,5,7],index=['A','B','C','D'])
sr2

A    1
B    3
C    5
D    7
dtype: int64

In [88]:
data={'ID':['1001','1002','1003','1004'],
    'Name':['Ann','Beth','Cathlyn','David'],
    'GPA':[3.51,2.75,3.04,2.24]}
df=pd.DataFrame(data)
df

     ID     Name   GPA
0  1001      Ann  3.51
1  1002     Beth  2.75
2  1003  Cathlyn  3.04
3  1004    David  2.24

In [89]:
data={'ID':['1001','1002','1003','1004'],
    'Name':['Ann','Beth','Cathlyn','David'],
    'GPA':[3.51,2.75,3.04,2.24]}
df2=pd.DataFrame(data,columns=['ID','Name','GPA'])
df2

     ID     Name   GPA
0  1001      Ann  3.51
1  1002     Beth  2.75
2  1003  Cathlyn  3.04
3  1004    David  2.24

## Basic Input/Output

In [16]:
df2.to_csv('student.csv',index=False)

In [17]:
df3=pd.read_csv('student.csv')
df3

     ID     Name   GPA
0  1001      Ann  3.51
1  1002     Beth  2.75
2  1003  Cathlyn  3.04
3  1004    David  2.24

In [21]:
df4=pd.read_csv('student.csv', sep=',', header='infer', index_col='ID')
df4

         Name   GPA
ID
1001      Ann  3.51
1002     Beth  2.75
1003  Cathlyn  3.04
1004    David  2.24

## Directory Setup Commands

In [82]:
import os
os.chdir('/Users/krittitee/ComPro_2')
os.getcwd()

'/Users/krittitee/ComPro_2'

## Basic Information

In [24]:
df3.shape

(4, 3)

In [25]:
df3.columns

Index(['ID', 'Name', 'GPA'], dtype='object')

In [27]:
df3.index

RangeIndex(start=0, stop=4, step=1)

In [28]:
df3.dtypes

ID        int64
Name     object
GPA     float64
dtype: object

In [29]:
df3.head()

     ID     Name   GPA
0  1001      Ann  3.51
1  1002     Beth  2.75
2  1003  Cathlyn  3.04
3  1004    David  2.24

In [30]:
sr.shape

(4,)

In [31]:
sr.dtypes

dtype('int64')

## Basic Indexing

In [32]:
df3['Name']

0        Ann
1       Beth
2    Cathlyn
3      David
Name: Name, dtype: object

In [33]:
df3[1:3]

     ID     Name   GPA
1  1002     Beth  2.75
2  1003  Cathlyn  3.04

In [34]:
df3[1:]

     ID     Name   GPA
1  1002     Beth  2.75
2  1003  Cathlyn  3.04
3  1004    David  2.24

In [41]:
df3[:2]

     ID  Name   GPA
0  1001   Ann  3.51
1  1002  Beth  2.75

### Indexing by label

In [90]:
df.loc[2:3]

     ID     Name   GPA
2  1003  Cathlyn  3.04
3  1004    David  2.24

In [43]:
df3.loc[2:3, 'Name']

2    Cathlyn
3      David
Name: Name, dtype: object

In [44]:
df3.loc[:, 'Name']

0        Ann
1       Beth
2    Cathlyn
3      David
Name: Name, dtype: object

In [45]:
df3.loc[[0,2],'Name':'GPA']

      Name   GPA
0      Ann  3.51
2  Cathlyn  3.04

In [47]:
df4.loc[1002:1003, 'Name']

ID
1002       Beth
1003    Cathlyn
Name: Name, dtype: object

### Indexing by integer

In [48]:
df4.iloc[2:4,0]

ID
1003    Cathlyn
1004      David
Name: Name, dtype: object

In [50]:
df4.iloc[2:4, 0:1]

         Name
ID
1003  Cathlyn
1004    David

In [51]:
df4.iloc[:3]

         Name   GPA
ID
1001      Ann  3.51
1002     Beth  2.75
1003  Cathlyn  3.04

In [52]:
df3.iloc[[0,2],[0,2]]

     ID   GPA
0  1001  3.51
2  1003  3.04

## Boolean Indexing

In [53]:
df3[df3.Name == 'Beth']

     ID  Name   GPA
1  1002  Beth  2.75

In [54]:
df3[df3.GPA>3]

     ID     Name   GPA
0  1001      Ann  3.51
2  1003  Cathlyn  3.04

In [55]:
df3[df3.GPA>3]['Name']

0        Ann
2    Cathlyn
Name: Name, dtype: object

In [56]:
df3[(df3.GPA>2.5)&(df3.GPA<3.5)]

     ID     Name   GPA
1  1002     Beth  2.75
2  1003  Cathlyn  3.04

In [60]:
df3[(df3.ID==1002)|(df3.GPA>3.0)]

     ID     Name   GPA
0  1001      Ann  3.51
1  1002     Beth  2.75
2  1003  Cathlyn  3.04

In [61]:
df3[df3.Name.isin(['Ann','David'])]

     ID   Name   GPA
0  1001    Ann  3.51
3  1004  David  2.24

## Sorting

In [65]:
df3.sort_values(by='GPA',ascending=False,inplace=False)

     ID     Name   GPA
0  1001      Ann  3.51
2  1003  Cathlyn  3.04
1  1002     Beth  2.75
3  1004    David  2.24

In [66]:
df3

     ID     Name   GPA
0  1001      Ann  3.51
1  1002     Beth  2.75
2  1003  Cathlyn  3.04
3  1004    David  2.24

In [68]:
df5=df3.copy()
df5.sort_values(by='GPA',ascending=True,inplace=True)
df5

     ID     Name   GPA
3  1004    David  2.24
1  1002     Beth  2.75
2  1003  Cathlyn  3.04
0  1001      Ann  3.51

In [69]:
df3

     ID     Name   GPA
0  1001      Ann  3.51
1  1002     Beth  2.75
2  1003  Cathlyn  3.04
3  1004    David  2.24

In [70]:
df5.sort_index(axis=0,ascending=False)

     ID     Name   GPA
3  1004    David  2.24
2  1003  Cathlyn  3.04
1  1002     Beth  2.75
0  1001      Ann  3.51

In [71]:
df5.sort_index(axis=1)

    GPA    ID     Name
3  2.24  1004    David
1  2.75  1002     Beth
2  3.04  1003  Cathlyn
0  3.51  1001      Ann

## Inserting

In [72]:
df3.loc[4]=['1005','David','2.32']
df3

     ID     Name   GPA
0  1001      Ann  3.51
1  1002     Beth  2.75
2  1003  Cathlyn  3.04
3  1004    David  2.24
4  1005    David  2.32

In [73]:
df3 = df3.assign(Gender=['F','F','F','M','M'])
df3

     ID     Name   GPA Gender
0  1001      Ann  3.51      F
1  1002     Beth  2.75      F
2  1003  Cathlyn  3.04      F
3  1004    David  2.24      M
4  1005    David  2.32      M

In [75]:
df3=df3.assign(Age=[22,20,19,22,21])
df3

     ID     Name   GPA Gender  Age
0  1001      Ann  3.51      F   22
1  1002     Beth  2.75      F   20
2  1003  Cathlyn  3.04      F   19
3  1004    David  2.24      M   22
4  1005    David  2.32      M   21

## Dropping

In [76]:
df4 = df3.copy()
df4

     ID     Name   GPA Gender  Age
0  1001      Ann  3.51      F   22
1  1002     Beth  2.75      F   20
2  1003  Cathlyn  3.04      F   19
3  1004    David  2.24      M   22
4  1005    David  2.32      M   21

In [77]:
df4.drop([1,3],axis=0)

     ID     Name   GPA Gender  Age
0  1001      Ann  3.51      F   22
2  1003  Cathlyn  3.04      F   19
4  1005    David  2.32      M   21

In [78]:
df4

     ID     Name   GPA Gender  Age
0  1001      Ann  3.51      F   22
1  1002     Beth  2.75      F   20
2  1003  Cathlyn  3.04      F   19
3  1004    David  2.24      M   22
4  1005    David  2.32      M   21

In [79]:
df4.drop([1,3],axis=0,inplace=True)

In [80]:
df4

     ID     Name   GPA Gender  Age
0  1001      Ann  3.51      F   22
2  1003  Cathlyn  3.04      F   19
4  1005    David  2.32      M   21

In [81]:
df4.drop(['Gender','Age'],axis=1)

     ID     Name   GPA
0  1001      Ann  3.51
2  1003  Cathlyn  3.04
4  1005    David  2.32